export const quickImportTypes = [
  'companies',
  'branches',
  'departments',
  'positions',
  'employees',
] as const;

export type QuickImportType = (typeof quickImportTypes)[number];

export type QuickImportColumn = {
  key: string;
  header: string;
  required: boolean;
  instructions: string;
  aliases: string[];
  example: string;
};

export type QuickImportConfig = {
  type: QuickImportType;
  label: string;
  description: string;
  requiresCompany: boolean;
  columns: QuickImportColumn[];
};

export const quickImportConfigs: Record<QuickImportType, QuickImportConfig> = {
  companies: {
    type: 'companies',
    label: 'Empresas',
    description: 'Importe várias empresas clientes e vincule automaticamente à clínica logada.',
    requiresCompany: false,
    columns: [
      {
        key: 'legal_name',
        header: 'razao_social',
        required: true,
        instructions: 'Razão social completa.',
        aliases: ['razao_social', 'razão_social', 'legal_name', 'razao social'],
        example: 'Empresa Exemplo S.A.',
      },
      {
        key: 'name',
        header: 'nome_fantasia',
        required: true,
        instructions: 'Nome fantasia ou nome público da empresa.',
        aliases: ['nome_fantasia', 'nome fantasia', 'empresa', 'name', 'nome'],
        example: 'Empresa Exemplo',
      },
      {
        key: 'cnpj',
        header: 'cnpj',
        required: true,
        instructions: 'CNPJ válido, com ou sem pontuação.',
        aliases: ['cnpj'],
        example: '12.345.678/0001-95',
      },
      {
        key: 'responsible_name',
        header: 'responsavel',
        required: true,
        instructions: 'Responsável principal na empresa.',
        aliases: ['responsavel', 'responsável', 'responsible_name', 'hr_responsible'],
        example: 'Ana Souza',
      },
      {
        key: 'email',
        header: 'email',
        required: true,
        instructions: 'E-mail corporativo do responsável.',
        aliases: ['email', 'e-mail'],
        example: 'ana@empresa.com.br',
      },
      {
        key: 'phone',
        header: 'telefone',
        required: true,
        instructions: 'Telefone de contato.',
        aliases: ['telefone', 'phone', 'celular'],
        example: '+55 11 99999-0000',
      },
      {
        key: 'segment',
        header: 'segmento',
        required: true,
        instructions: 'Segmento de atuação.',
        aliases: ['segmento', 'segment', 'setor'],
        example: 'Tecnologia',
      },
      {
        key: 'city',
        header: 'cidade',
        required: true,
        instructions: 'Cidade da sede.',
        aliases: ['cidade', 'city', 'municipio', 'município'],
        example: 'São Paulo',
      },
      {
        key: 'state',
        header: 'estado',
        required: true,
        instructions: 'UF com 2 letras.',
        aliases: ['estado', 'uf', 'state'],
        example: 'SP',
      },
      {
        key: 'zip_code',
        header: 'cep',
        required: true,
        instructions: 'CEP com ou sem pontuação.',
        aliases: ['cep', 'zip_code', 'zipcode'],
        example: '01001-000',
      },
      {
        key: 'address',
        header: 'endereco',
        required: true,
        instructions: 'Logradouro/endereço.',
        aliases: ['endereco', 'endereço', 'address', 'logradouro'],
        example: 'Av. Paulista',
      },
      {
        key: 'address_number',
        header: 'numero',
        required: false,
        instructions: 'Número do endereço, se houver.',
        aliases: ['numero', 'número', 'number', 'address_number'],
        example: '1000',
      },
      {
        key: 'employee_count',
        header: 'numero_estimado_colaboradores',
        required: true,
        instructions: 'Número estimado de colaboradores.',
        aliases: [
          'numero_estimado_colaboradores',
          'número_estimado_colaboradores',
          'colaboradores',
          'employee_count',
        ],
        example: '250',
      },
      {
        key: 'status',
        header: 'status',
        required: true,
        instructions: 'Use ativo, inativo ou arquivado.',
        aliases: ['status', 'situacao', 'situação'],
        example: 'ativo',
      },
    ],
  },
  branches: {
    type: 'branches',
    label: 'Filiais',
    description: 'Importe filiais para uma empresa selecionada.',
    requiresCompany: true,
    columns: [
      {
        key: 'name',
        header: 'nome_filial',
        required: true,
        instructions: 'Nome da filial.',
        aliases: ['nome_filial', 'filial', 'name', 'nome'],
        example: 'Matriz São Paulo',
      },
      {
        key: 'cnpj',
        header: 'cnpj_filial',
        required: false,
        instructions: 'CNPJ da filial, se houver.',
        aliases: ['cnpj_filial', 'cnpj', 'cnpj da filial'],
        example: '12.345.678/0002-76',
      },
      {
        key: 'city',
        header: 'cidade',
        required: true,
        instructions: 'Cidade.',
        aliases: ['cidade', 'city', 'municipio', 'município'],
        example: 'São Paulo',
      },
      {
        key: 'state',
        header: 'estado',
        required: true,
        instructions: 'UF com 2 letras.',
        aliases: ['estado', 'uf', 'state'],
        example: 'SP',
      },
      {
        key: 'address',
        header: 'endereco',
        required: true,
        instructions: 'Endereço da filial.',
        aliases: ['endereco', 'endereço', 'address', 'logradouro'],
        example: 'Rua das Flores, 10',
      },
      {
        key: 'responsible_name',
        header: 'responsavel',
        required: true,
        instructions: 'Responsável pela filial.',
        aliases: ['responsavel', 'responsável', 'responsible_name'],
        example: 'Carlos Lima',
      },
      {
        key: 'phone',
        header: 'telefone',
        required: true,
        instructions: 'Telefone de contato.',
        aliases: ['telefone', 'phone', 'celular'],
        example: '+55 11 98888-1111',
      },
      {
        key: 'email',
        header: 'email',
        required: true,
        instructions: 'E-mail da filial/responsável.',
        aliases: ['email', 'e-mail'],
        example: 'filial.sp@empresa.com.br',
      },
      {
        key: 'status',
        header: 'status',
        required: true,
        instructions: 'Use ativo, inativo ou arquivado.',
        aliases: ['status', 'situacao', 'situação'],
        example: 'ativo',
      },
    ],
  },
  departments: {
    type: 'departments',
    label: 'Departamentos',
    description: 'Importe departamentos para uma empresa selecionada.',
    requiresCompany: true,
    columns: [
      {
        key: 'name',
        header: 'nome_departamento',
        required: true,
        instructions: 'Nome do departamento.',
        aliases: ['nome_departamento', 'departamento', 'department', 'name', 'nome'],
        example: 'Recursos Humanos',
      },
      {
        key: 'branch_name',
        header: 'filial',
        required: false,
        instructions: 'Filial existente, se aplicável.',
        aliases: ['filial', 'branch', 'branch_name', 'nome_filial'],
        example: 'Matriz São Paulo',
      },
      {
        key: 'responsible_name',
        header: 'responsavel',
        required: true,
        instructions: 'Responsável pelo departamento.',
        aliases: ['responsavel', 'responsável', 'responsible_name'],
        example: 'Beatriz Rocha',
      },
      {
        key: 'status',
        header: 'status',
        required: true,
        instructions: 'Use ativo, inativo ou arquivado.',
        aliases: ['status', 'situacao', 'situação'],
        example: 'ativo',
      },
    ],
  },
  positions: {
    type: 'positions',
    label: 'Cargos',
    description: 'Importe cargos para uma empresa selecionada.',
    requiresCompany: true,
    columns: [
      {
        key: 'name',
        header: 'nome_cargo',
        required: true,
        instructions: 'Nome do cargo.',
        aliases: ['nome_cargo', 'cargo', 'position', 'name', 'nome'],
        example: 'Analista de RH',
      },
      {
        key: 'department_name',
        header: 'departamento',
        required: false,
        instructions: 'Departamento existente, se aplicável.',
        aliases: ['departamento', 'department', 'department_name', 'nome_departamento'],
        example: 'Recursos Humanos',
      },
      {
        key: 'cbo_code',
        header: 'cbo',
        required: false,
        instructions: 'Código CBO, se houver.',
        aliases: ['cbo', 'cbo_code', 'codigo_cbo', 'código_cbo'],
        example: '2524-05',
      },
      {
        key: 'description',
        header: 'descricao',
        required: true,
        instructions: 'Descrição resumida da função.',
        aliases: ['descricao', 'descrição', 'description'],
        example: 'Atua nos processos de gestão de pessoas.',
      },
      {
        key: 'status',
        header: 'status',
        required: true,
        instructions: 'Use ativo, inativo ou arquivado.',
        aliases: ['status', 'situacao', 'situação'],
        example: 'ativo',
      },
    ],
  },
  employees: {
    type: 'employees',
    label: 'Colaboradores',
    description: 'Importe colaboradores em massa com validação de estrutura organizacional.',
    requiresCompany: true,
    columns: [
      {
        key: 'full_name',
        header: 'nome',
        required: true,
        instructions: 'Nome completo do colaborador.',
        aliases: ['nome', 'full_name', 'nome_completo', 'colaborador'],
        example: 'João Pereira',
      },
      {
        key: 'cpf',
        header: 'cpf',
        required: true,
        instructions: 'CPF válido, com ou sem pontuação.',
        aliases: ['cpf'],
        example: '123.456.789-09',
      },
      {
        key: 'email',
        header: 'email',
        required: true,
        instructions: 'E-mail único do colaborador.',
        aliases: ['email', 'e-mail'],
        example: 'joao.pereira@empresa.com.br',
      },
      {
        key: 'phone',
        header: 'telefone',
        required: true,
        instructions: 'Telefone de contato.',
        aliases: ['telefone', 'phone', 'celular'],
        example: '+55 11 97777-2222',
      },
      {
        key: 'birth_date',
        header: 'data_nascimento',
        required: true,
        instructions: 'Data em DD/MM/AAAA ou AAAA-MM-DD.',
        aliases: ['data_nascimento', 'nascimento', 'birth_date'],
        example: '15/03/1990',
      },
      {
        key: 'gender',
        header: 'sexo',
        required: true,
        instructions: 'Use M, F, O ou N.',
        aliases: ['sexo', 'genero', 'gênero', 'gender'],
        example: 'M',
      },
      {
        key: 'branch_name',
        header: 'filial',
        required: true,
        instructions: 'Nome da filial.',
        aliases: ['filial', 'branch', 'branch_name', 'nome_filial'],
        example: 'Matriz São Paulo',
      },
      {
        key: 'department_name',
        header: 'departamento',
        required: true,
        instructions: 'Nome do departamento.',
        aliases: ['departamento', 'department', 'department_name', 'nome_departamento'],
        example: 'Recursos Humanos',
      },
      {
        key: 'position_name',
        header: 'cargo',
        required: true,
        instructions: 'Nome do cargo.',
        aliases: ['cargo', 'position', 'position_name', 'nome_cargo'],
        example: 'Analista de RH',
      },
      {
        key: 'city',
        header: 'cidade',
        required: true,
        instructions: 'Cidade do colaborador.',
        aliases: ['cidade', 'city', 'municipio', 'município'],
        example: 'São Paulo',
      },
      {
        key: 'state',
        header: 'estado',
        required: true,
        instructions: 'UF com 2 letras.',
        aliases: ['estado', 'uf', 'state'],
        example: 'SP',
      },
      {
        key: 'admission_date',
        header: 'data_admissao',
        required: true,
        instructions: 'Data em DD/MM/AAAA ou AAAA-MM-DD.',
        aliases: ['data_admissao', 'admissao', 'admissão', 'admission_date'],
        example: '01/02/2024',
      },
      {
        key: 'status',
        header: 'status',
        required: true,
        instructions: 'Use ativo, inativo ou arquivado.',
        aliases: ['status', 'situacao', 'situação'],
        example: 'ativo',
      },
    ],
  },
};

export const quickImportTypeLabels = Object.fromEntries(
  quickImportTypes.map((type) => [type, quickImportConfigs[type].label])
) as Record<QuickImportType, string>;
